### ISSUE TITLE
As a user I want to create notice boards

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#26]
**Description:**

Users with the valid rights can create new notice boards. By that they become the "creator" of the new board and has Super-User rights on it. Creators can add users to their notice boards and manage the content on it.

**Subtasks:**
- [x] #141

**Acceptance criteria:**
- [x] Users with the according permission can create new notice boards 
- [x] These users become creators for the new board
 
**Test case (use Jest):**
- [x] Try to create a new notice board, then check table "Board" in the database for fitting entry
